name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to fill out this bug report. 

        Help us help you! Please explain the problem and your expected result.
        The questions below show the information we need to properly
        reproduce and fix the bug, solving your problem quicker.

  - type: checkboxes
    id: checks
    attributes:
      label: Version Checks
      description: Please confirm you have checked the following.
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the latest version.
          required: true
        - label: >
            I have confirmed this bug exists on the main branch.
          required: true

  - type: textarea
    id: example
    attributes:
      label: Reproducible Code Example
      description: >
        Please provide a simple example of code which can reproduce the bug.
        [This guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
        explains how to provide a minimal, copy-pastable example.
      render: python

  - type: textarea
    id: error
    attributes:
      label: Error Message / Traceback
      description: >
        If an error message occurred, please paste the full message (or traceback) here.
      value: >
        <details>


        Replace this line with the full error message or traceback.


        </details>

  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example.
      placeholder: >
        X does not produce the desired result when I...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
      placeholder: >
        I would have expected the following to happen...
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: >
        Please outline the versions of all installed packages
        e.g. paste the output of `conda list` or `pip list`.
      value: >
        <details>


        Replace this line with the output `conda list` or `pip list`.


        </details>
    validations:
      required: true
