name: Documentation Improvement
description: Report wrong or missing documentation
title: "[Docs]: "
labels: [documentation]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking time to suggest this documentation improvement.

        Please provide information to explain what is unclear, or missing from,
        the documentation and an explanation of your suggestion for improvement. 

  - type: checkboxes
    attributes:
      label: Version checks
      options:
        - label: >
            I have checked that the issue still exists on the latest versions on read the docs.
          required: true

  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation, e.g. "caf.toolkit.CostDistribution" or the
        URL of the documentation, e.g.
        "https://caftoolkit.readthedocs.io/en/latest/_autosummary/caf.toolkit.cost_utils.CostDistribution.html"
      placeholder: https://caftoolkit.readthedocs.io/en/latest/_autosummary/caf.toolkit.cost_utils.CostDistribution.html
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs to be
        added, fixed or improved.
      placeholder: >
        The explanation of X is missing / not clear... / doesn't explain...
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please explain the suggested fix and **why** it's better than the existing documentation.
      placeholder: >
        The documentation of X should include... / be rewritten to... / be removed

        Because ...
    validations:
      required: true
