name: Feature Request
description: Suggest an new feature / change to the functionality.
title: "[Feat]: "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking time to suggest this feature or improvement.

        Please describe the problem this feature will improve before explaining the 
        details of the feature itself. If there is a current workaround please include 
        any information about this and why the new feature would be better.

        Please use the "Additional Context" question to note if this feature
        requires specific inputs, outputs, or you have an example implementation.

  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality
        - label: >
            Changing existing functionality
        - label: >
            Removing existing functionality

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve.
      placeholder: >
        Add method to write cost distributions to CSVs.
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using psudocode if relevant.
      placeholder: >
        Update the CostDistribution class with a new `to_csv` method which takes a filepath
        and writes the cost distribution table to it.
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        Please describe any alternative solution (existing functionality, 3rd party package, etc.)
        that would satisfy the feature request.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe
        and support the feature request.
      placeholder: >
        This could include an example implementation of the feature in full or
        links to additional resources which aid understanding.
