name: Feature Request
description: Suggest a new feature or change to existing functionality.
title: "[Feat]: "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking time to suggest this feature or improvement.

        Please describe the problem this feature will improve before explaining the 
        details of the feature itself. If there is a current workaround please include 
        any information about this and why the new feature would be better.

        Please use the "Additional Context" question to note if this feature
        requires specific inputs, outputs, or you have an example implementation.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: Adding new functionality
          value: adding
        - label: Changing existing functionality
          value: changing
        - label: Removing existing functionality
          value: removing
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        What issue or user need does this feature address?
        Describe the current behaviour and why it is inadequate.
      placeholder: >
        e.g. The repository contains hard-coded secrets in `appsettings.json`,
        exposing credentials to anyone with repo access.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: >
        What are the risks or consequences if this problem is not addressed?
        Consider security, compliance, maintainability or user experience.
      placeholder: >
        e.g. Unauthorised access to production database; difficulty rotating credentials;
        non-compliance with security policies.
    validations:
      required: true

  - type: textarea
    id: proposed-approach
    attributes:
      label: Proposed Approach
      description: >
        Outline the steps or design you recommend to resolve the problem.
        Reference technologies, config files or workflows where applicable.
      placeholder: >
        e.g. Remove secrets from config file; replace with environment variables
        injected via GitHub Actions; configure Azure App Service settings accordingly.
    validations:
      required: false

  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        What other options did you consider?
        List pros and cons of each to explain why they were not chosen.
      placeholder: >
        e.g. Use Azure Key Vault with managed identity (more secure but requires extra infra);
        .NET User Secrets for local dev (not suitable for production).
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe
        and support the feature request.
      placeholder: >
        This could include an example implementation of the feature in full or
        links to additional resources which aid understanding.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: >
        Define clear, measurable conditions that must be met for this feature
        to be considered complete and ready for review.
      placeholder: |
        - `appsettings.json` contains no real secrets  
        - GitHub Actions workflow injects required environment variables  
        - Azure App Service settings match injected variables  
        - Application builds, deploys and runs correctly in each environment
    validations:
      required: true
